# pod is the samllest deployable unit in k8's, pod can have multiple containers

kind: pod
apiVersion: v1
metadata:
 name: nginx
 namespace: expense
spec:
 #onepos can contain multiple ontainrs
 containers:
 - name: nginx
   image: nginx
 

