#Labels are key value pairs to which is used to define project details
kind: Pod
apiVersion: v1
metadata:
 name: labels
 labels: 
  project: expense
  end: dev
  components: backend
spec:
 containers:
 - name: nginx
   image: nginx
   
